### PR TITLE
Fix integer overflow in consume_integer() 

### LINKED ISSUE #29: Integer overflow in consume_integer()
```lua
[0] ~/sources/luzer $ tarantool
Tarantool 2.11.5-0-g12a9ceb870c
type 'help' for interactive help
tarantool> luzer = require('luzer')
---
...

tarantool> fdp = luzer.FuzzedDataProvider("12093810923801928309128309128021983")
---
...

tarantool> fdp:consume_integer(1, 2^51)
---
- error: min must be less than or equal to max
...

tarantool>
```

Version: 59877a2870652c16ec912a6b969e2c6cac1e34b5

### PR DESCRIPTION
**Pull request by ligurio**
Fixes #29

### CODE REVIEW

File: luzer/tests/test_unit.lua [hunk 1]
```diff
@@ -120,6 +120,9 @@ ok, err = pcall(fdp.consume_number)
 assert(ok == false)
 assert(err ~= nil)
 
+local n = fdp:consume_number(1, MAX_INT)
```
Comment (Buristan) [inline luzer/tests/test_unit.lua:123]: This check looks suspicious and unrelated to this commit (or I don't get it). Also, `MAX_INT` isn't defined yet.

File: luzer/tests/test_unit.lua [hunk 2]
```diff
@@ -16,6 +16,8 @@ local err
 local fdp
 local res
 
+local MAX_INT = 2^51
```
Comment (Buristan) [inline luzer/tests/test_unit.lua:19]: I would rather use `MAX_INT64 = 0x7fffffffffffffff` instead to show the overflow.

File: luzer/tests/test_unit.lua [hunk 3]
```diff
@@ -145,6 +147,9 @@ ok, err = pcall(fdp.consume_integer)
 assert(ok == false)
 assert(err ~= nil)
 
+local i = fdp:consume_integer(1, MAX_INT)
```
Comment (Buristan) [inline luzer/tests/test_unit.lua:153]: It is better to use `MAX_INT, MAX_INT` to check both min and max values. And check the returned value below to be equal.

File: luzer/fuzzed_data_provider.cc [hunk 4]
```diff
@@ -185,14 +185,14 @@ luaL_consume_integers(lua_State *L)
...
+	lua_Integer count = luaL_checkinteger(L, 2);
+	lua_Integer min = luaL_checkinteger(L, 3);
+	lua_Integer max = luaL_checkinteger(L, 4);
 	if (min > max)
 		luaL_error(L, "min must be less than or equal to max");
 
 	lua_newtable(L);
-	for (int i = 1; i <= (int)count; i++) {
+	for (lua_Integer i = 1; i <= (lua_Integer)count; i++) {
 		auto number = lfdp->fdp->ConsumeIntegralInRange(min, max);
```
Comment (Buristan) [inline luzer/fuzzed_data_provider.cc:193]: Minor: Maybe it is better to set type to `lua_Integer` here explicitly. Feel free to ignore.

**Review by Buristan — CHANGES_REQUESTED** [review]

File: luzer/tests/test_unit.lua (hunk 2 above)
Comment (ligurio) [reply luzer/tests/test_unit.lua]: Fixed:

```diff
--- a/luzer/tests/test_unit.lua
+++ b/luzer/tests/test_unit.lua
@@ -16,7 +16,18 @@ local err
 local fdp
 local res
 
-local MAX_INT = 2^51
+-- By default `lua_Integer` is long long, (usually a 64-bit
+-- two-complement integer), but that can be changed to long or
+-- int (usually a 32-bit two-complement integer), see LUA_INT_TYPE
+-- in <luaconf.h>. Lua 5.3+ has two functions:
+-- `math.maxinteger` and `math.mininteger` that returns an integer
+-- with the maximum value for an integer and an integer with the
+-- minimum value for an integer, see [1].
+--
+-- 1. https://www.lua.org/manual/5.3/manual.html#lua_Integer
+local MAX_INT64 = 0x7fffffffffffffff
+local MAX_INT = math.maxinteger or MAX_INT64
+local MIN_INT = math.mininteger or -MAX_INT64
 
 -- luzer.FuzzedDataProvider()
 assert(type(luzer.FuzzedDataProvider) == "function")
```

File: luzer/tests/test_unit.lua (hunk 3 above)
Comment (ligurio) [reply luzer/tests/test_unit.lua]: Added:

```lua
local max_int = fdp:consume_integer(MAX_INT, MAX_INT)
assert(type(max_int) == "number")
assert(max_int == MAX_INT)

local min_int = fdp:consume_integer(MIN_INT, MIN_INT)
assert(type(min_int) == "number")
assert(min_int == MIN_INT)

local i = fdp:consume_integer(MIN_INT, MAX_INT)
assert(type(i) == "number")
```
