### PR TITLE
luzer: fix arguments order in FDP functions

### LINKED ISSUE #44: Wrong arguments order in FDP functions `consume_integers()` and `consume_numbers()`
`consume_integers()`:

```lua
> luzer = require('luzer')
> fdp = luzer.FuzzedDataProvider(string.rep('XYZ', 100))
> fdp:consume_integers(0, 0x7fffffff, 3)
---
- error: min must be less than or equal to max
...

> fdp:consume_integers(3, 0, 0x7fffffff)
---
- - 1515804762
  - 1498962521
  - 1482316120
...

> 
```

`consume_numbers()`:

```lua
> fdp:consume_numbers(0, 0x7fffffff, 3)
---
- error: min must be less than or equal to max
...

> fdp:consume_numbers(3, 0, 0x7fffffff)
---
- - 757902380.82158
  - 741158059.83133
  - 749481260.32356
...

> 
```

Version: bc791dc5656b4f7238402155651f6927fae39faa

### PR DESCRIPTION
**Pull request by ligurio**
Fixes #44

### CODE REVIEW

File: luzer/tests/test_unit.lua [hunk 1]
```diff
@@ -146,14 +146,18 @@ local num = fdp:consume_number(1, MAX_INT)
...
 
 -- luzer.FuzzedDataProvider.consume_numbers()
-fdp = luzer.FuzzedDataProvider("ABCDEF")
+fdp = luzer.FuzzedDataProvider(string.rep("XYZ", 100))
 assert(type(fdp.consume_numbers) == "function")
 
-res = fdp:consume_numbers(2, 1, 3)
+local min = 1
+local max = MAX_INT
+res = fdp:consume_numbers(min, max, 3)
```
Comment (Buristan) [inline luzer/tests/test_unit.lua:154]: I suppose it is good to check that `#res == 3` as requested.

File: luzer/tests/test_unit.lua [hunk 2]
```diff
@@ -184,17 +188,18 @@ local i = fdp:consume_integer(MIN_INT, MAX_INT)
...
-fdp = luzer.FuzzedDataProvider("AB")
+fdp = luzer.FuzzedDataProvider(string.rep("XYZ", 100))
 assert(type(fdp.consume_integers) == "function")
 
-local min = 1
-local max = 6
-res = fdp:consume_integers(1, min, max)
+min = 1
+max = MAX_INT
+res = fdp:consume_integers(min, max, 3)
```
Comment (Buristan) [inline luzer/tests/test_unit.lua:196]: I suppose it is good to check that `#res == 3` as requested.

**Review by Buristan — APPROVED** [review]
LGTM, with two minor comments below.

File: luzer/tests/test_unit.lua (hunk 1 above)
Comment (ligurio) [reply luzer/tests/test_unit.lua:154]: Fixed:

```diff
--- a/luzer/tests/test_unit.lua
+++ b/luzer/tests/test_unit.lua
@@ -151,8 +151,10 @@ assert(type(fdp.consume_numbers) == "function")
 
 local min = 1
 local max = MAX_INT
-res = fdp:consume_numbers(min, max, 3)
+local count = 3
+res = fdp:consume_numbers(min, max, count)
 assert(type(res) == "table")
+assert(#res == count)
 for _, n in ipairs(res) do
     assert(type(n) == "number")
     assert(n <= max)
```
