### PR TITLE
luzer: fix arguments checking in Fuzz()

### LINKED ISSUE #41: Fix parameters checking in luzer.Fuzz()
No parameters:

```
> luzer.Fuzz()
---
- error: '/home/sergeyb/sources/luzer/luzer/init.lua:37: bad argument #1 to ''pairs''
    (table expected, got nil)'
...
```

Passed only `TestOneInput()`:

```
> luzer.Fuzz(f)
---
- error: '/home/sergeyb/sources/luzer/luzer/init.lua:37: bad argument #1 to ''pairs''
    (table expected, got nil)'
...

> 
```

Passed only `TestOneInput()` and a custom mutator function:

```
tarantool> luzer.Fuzz(f, nil)
---
- error: '/home/sergeyb/sources/luzer/luzer/init.lua:37: bad argument #1 to ''pairs''
    (table expected, got nil)'
...
```

Also: Update API section with parameters in documentation [^1] and mark argument with custom mutator function and `arg` table as optional.

Version: 3945352537f4e99edecb5893362f4f71345c33ed

[^1]: https://github.com/ligurio/luzer/blob/3945352537f4e99edecb5893362f4f71345c33ed/docs/api.md?plain=1#L10-L19

### PR DESCRIPTION
**Pull request by ligurio**
Follows up commit 649289aa945b
("luzer: support command-line options").

Fixes #41

### CODE REVIEW

File: luzer/tests/test_unit.lua [hunk 1]
```diff
@@ -289,4 +289,20 @@ for _, testcase in ipairs(flag_testcases) do
...
+ok, err = pcall(luzer.Fuzz, {})
+assert(ok == false)
+assert(err:match("test_one_input is not a Lua function") ~= nil)
+
+-- Call `Fuzz()` with a table instead a custom mutator function
+-- and a function instead a table with arguments.
+ok, err = pcall(luzer.Fuzz, function() end, {}, function() end)
+assert(ok == false)
+assert(err:match("`custom_mutator` must be a function") ~= nil)
+
```
Comment (Buristan) [inline luzer/tests/test_unit.lua:307]: It would be nice to check the non-table argument as well.
Feel free to ignore.

File: luzer/init.lua [hunk 2]
```diff
@@ -53,7 +53,15 @@ local function progname(argv)
 end
 
 local function Fuzz(test_one_input, custom_mutator, func_args)
-    local flags = build_flags(arg, func_args)
+    if custom_mutator ~= nil and
+       type(custom_mutator) ~= "function" then
+        error("`custom_mutator` must be a function")
```
Comment (Buristan) [inline luzer/init.lua:58]: You may also reformat this part as the following (it looks more readable to me):
```lua
    if custom_mutator ~= nil and
       type(custom_mutator) ~= "function"
    then
        error("`custom_mutator` must be a function")
    end
```
Feel free to ignore, though.

**Review by Buristan — APPROVED** [review]
Hi, Sergey!
Thanks for the patch!
LGTM, with ignorable suggestions below.

File: luzer/tests/test_unit.lua (hunk 1 above)
Comment (ligurio) [reply luzer/tests/test_unit.lua:307]: Added testcase with number:

```diff
+-- Call `Fuzz()` with a number instead a table with arguments.
+ok, err = pcall(luzer.Fuzz, function() end, nil, 42)
+assert(ok == false)
+assert(err:match("args is not a table") ~= nil)
 
 print("Success!")
```

File: luzer/init.lua (hunk 2 above)
Comment (ligurio) [reply luzer/init.lua]: Updated:

```diff
--- a/luzer/init.lua
+++ b/luzer/init.lua
@@ -54,7 +54,8 @@ end
 
 local function Fuzz(test_one_input, custom_mutator, func_args)
     if custom_mutator ~= nil and
-       type(custom_mutator) ~= "function" then
+       type(custom_mutator) ~= "function"
+    then
         error("custom_mutator must be a function")
     end
     local luzer_args = func_args or {}
```
