### PR TITLE
luzer: fix running with -jobs option

### LINKED ISSUE #32: libFuzzer option -jobs does not work
```
[0] ~/sources/luzer $ LUA_PATH="./luzer/?.lua;;" LUA_CPATH="./build/luzer/?.so;./build/luzer/test/?.so;;" tarantool examples/example_basic.lua -jobs=3
Running 3 workers
<test name> -only_ascii=1 -print_pcs=1 >fuzz-0.log 2>&1
<test name> -only_ascii=1 -print_pcs=1 >fuzz-1.log 2>&1
<test name> -only_ascii=1 -print_pcs=1 >fuzz-2.log 2>&1
sh: 1: cannot open test: No such file
sh: 1: sh: 1: cannot open test: No such filecannot open test: No such file

================== Job 2 exited with exit code 2 ============
================== Job 0 exited with exit code 2 ============
================== Job 1 exited with exit code 2 ============
```

### PR DESCRIPTION
**Pull request by ligurio**
The commit d777927e538b ("luzer: fix argv building") sets `argv[0]` to a constant value on the assumption that it is not used anywhere. But `argv[0]` is used in running a test by multiple processes. The patch fixes an `argv[0]` by setting it to a command and it's first argument with path to test.

Fixes #32

### CODE REVIEW

File: luzer/luzer.c [hunk 1]
```diff
@@ -353,7 +356,7 @@ luaL_fuzz(lua_State *L)
 	if (!argv)
 		luaL_error(L, "not enough memory");
 
-	argv[0] = "<test name>";
+	argv[0] = argv_0;
```
Comment (Buristan) [inline luzer/luzer.c:359]: I don't see the clean up of this string. It should be freed after the end of the run.

**Review by Buristan — CHANGES_REQUESTED** [review]
Hi, Sergey!
Thanks for the patch!
LGTM, with two comments below.

File: luzer/luzer.c (hunk 1 above)
Comment (ligurio) [reply luzer/luzer.c:359]: Thanks!

```diff
--- a/luzer/luzer.c
+++ b/luzer/luzer.c
@@ -336,7 +336,7 @@ NO_SANITIZE static void
 free_argv(int argc, char **argv)
 {
        /* Free allocated argv strings and the buffer. */
-       for (int i = 1; i < argc; i++)
+       for (int i = 0; i < argc; i++)
                free(argv[i]);
        free(argv);
 }
```

File: luzer/init.lua [hunk 2]
```diff
@@ -45,7 +45,10 @@ end
 
 local function Fuzz(test_one_input, custom_mutator, func_args)
     local flags = build_flags(arg, func_args)
-    luzer_impl.Fuzz(test_one_input, custom_mutator, flags)
+    local test_path = arg[0]
+    local lua_bin = arg[-1]
```
[the remark this answers is not in the document]
Comment (ligurio) [reply luzer/init.lua:49]: Thanks! Fixed and updated test:

```diff
diff --git a/luzer/init.lua b/luzer/init.lua
index c18d5cc..592f03d 100644
--- a/luzer/init.lua
+++ b/luzer/init.lua
@@ -43,10 +43,19 @@ local function build_flags(arg, func_args)
     return flags
 end
 
+local function progname(argv)
+    -- arg[-1] is guaranteed to be not nil.
+    local idx = -2
+    while argv[idx] do
+        idx = idx - 1
+    end
+    return argv[idx + 1]
+end
+
 local function Fuzz(test_one_input, custom_mutator, func_args)
     local flags = build_flags(arg, func_args)
     local test_path = arg[0]
-    local lua_bin = arg[-1]
+    local lua_bin = progname(arg)
     local test_cmd = ("%s %s"):format(lua_bin, test_path)
     luzer_impl.Fuzz(test_one_input, custom_mutator, flags, test_cmd)
 end
diff --git a/luzer/tests/CMakeLists.txt b/luzer/tests/CMakeLists.txt
index 845ecf9..db0f668 100644
--- a/luzer/tests/CMakeLists.txt
+++ b/luzer/tests/CMakeLists.txt
@@ -66,7 +66,7 @@ set_tests_properties(luzer_options_seed_via_option_test PROPERTIES
 
 add_test(
   NAME luzer_options_jobs_test
-  COMMAND ${LUA_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/test_options_2.lua
+  COMMAND ${LUA_EXECUTABLE} -e "a = 1" ${CMAKE_CURRENT_SOURCE_DIR}/test_options_2.lua
           -runs=10 -jobs=5
   WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
 )

```

**Review by Buristan — APPROVED** [review]
Thanks for the fixes!
LGTM!
